//! InfiniteScroll preview is generated by `#[component_doc]` in `orbital`.
pub use uf_product::components::OrbitalInfiniteScrollPreview;
pub use uf_product::components::OrbitalInfiniteScrollPreview as InfiniteScrollPreview;
