//! Static preview registrations for hand-written preview pages (Tier C).

use leptos::prelude::*;
use uf_product::preview::PreviewRegistration;

#[cfg(feature = "record-history")]
use crate::components::components::HistoryTimelinePreview;
#[cfg(feature = "tag-catalog")]
use crate::components::components::TagCatalogPickerPreview;
use crate::components::components::UnifiedFieldIconsPreview;
use crate::preview::fixtures::SearchSourcePickerPreview;

/// Manual registration for the search-source-picker preview page.
pub static SEARCH_SOURCE_PICKER_PREVIEW_REGISTRATION: PreviewRegistration = PreviewRegistration {
    slug: "search-source-picker",
    label: "Search Source Picker",
    section: "Integrations",
    section_priority: 50,
    category: "Unified Field",
    category_priority: 100,
    category_default_collapsed: false,
    group: "",
    group_priority: 0,
    nav_item: false,
    icon: icondata::AiSearchOutlined,
    render: || SearchSourcePickerPreview().into_any(),
};

/// Manual registration for the history-timeline preview page.
#[cfg(feature = "record-history")]
pub static HISTORY_TIMELINE_PREVIEW_REGISTRATION: PreviewRegistration = PreviewRegistration {
    slug: "history-timeline",
    label: "History Timeline",
    section: "Integrations",
    section_priority: 50,
    category: "Unified Field",
    category_priority: 100,
    category_default_collapsed: false,
    group: "",
    group_priority: 0,
    nav_item: false,
    icon: icondata::AiHistoryOutlined,
    render: || HistoryTimelinePreview().into_any(),
};

/// Manual registration for the tag-catalog-picker preview page.
#[cfg(feature = "tag-catalog")]
pub static TAG_CATALOG_PICKER_PREVIEW_REGISTRATION: PreviewRegistration = PreviewRegistration {
    slug: "tag-catalog-picker",
    label: "Tag Catalog Picker",
    section: "Integrations",
    section_priority: 50,
    category: "Unified Field",
    category_priority: 100,
    category_default_collapsed: false,
    group: "",
    group_priority: 0,
    nav_item: false,
    icon: icondata::AiTagOutlined,
    render: || TagCatalogPickerPreview().into_any(),
};

/// Manual registration for the Unified Field icons preview page.
pub static UNIFIED_FIELD_ICONS_PREVIEW_REGISTRATION: PreviewRegistration = PreviewRegistration {
    slug: "icons/unified-field",
    label: "Unified Field",
    section: "Integrations",
    section_priority: 50,
    category: "Unified Field",
    category_priority: 100,
    category_default_collapsed: false,
    group: "",
    group_priority: 0,
    nav_item: false,
    icon: icondata::AiAppstoreOutlined,
    render: || UnifiedFieldIconsPreview().into_any(),
};

/// Manual preview pages that are not generated by `#[component_doc]`.
pub fn all() -> &'static [&'static PreviewRegistration] {
    #[cfg(all(feature = "record-history", feature = "tag-catalog"))]
    {
        static REGS: &[&PreviewRegistration] = &[
            &SEARCH_SOURCE_PICKER_PREVIEW_REGISTRATION,
            &HISTORY_TIMELINE_PREVIEW_REGISTRATION,
            &TAG_CATALOG_PICKER_PREVIEW_REGISTRATION,
            &UNIFIED_FIELD_ICONS_PREVIEW_REGISTRATION,
        ];
        return REGS;
    }
    #[cfg(all(feature = "record-history", not(feature = "tag-catalog")))]
    {
        static REGS: &[&PreviewRegistration] = &[
            &SEARCH_SOURCE_PICKER_PREVIEW_REGISTRATION,
            &HISTORY_TIMELINE_PREVIEW_REGISTRATION,
            &UNIFIED_FIELD_ICONS_PREVIEW_REGISTRATION,
        ];
        return REGS;
    }
    #[cfg(all(not(feature = "record-history"), feature = "tag-catalog"))]
    {
        static REGS: &[&PreviewRegistration] = &[
            &SEARCH_SOURCE_PICKER_PREVIEW_REGISTRATION,
            &TAG_CATALOG_PICKER_PREVIEW_REGISTRATION,
            &UNIFIED_FIELD_ICONS_PREVIEW_REGISTRATION,
        ];
        return REGS;
    }
    #[cfg(all(not(feature = "record-history"), not(feature = "tag-catalog")))]
    {
        static REGS: &[&PreviewRegistration] = &[
            &SEARCH_SOURCE_PICKER_PREVIEW_REGISTRATION,
            &UNIFIED_FIELD_ICONS_PREVIEW_REGISTRATION,
        ];
        REGS
    }
}
