//! Static preview registrations for hand-written preview pages (Tier C).

use leptos::prelude::*;
use uf_product::preview::PreviewRegistration;

use crate::components::components::UnifiedFieldIconsPreview;
use crate::preview::fixtures::SearchSourcePickerPreview;

/// Manual registration for the search-source-picker preview page.
pub static SEARCH_SOURCE_PICKER_PREVIEW_REGISTRATION: PreviewRegistration = PreviewRegistration {
    slug: "search-source-picker",
    label: "Search Source Picker",
    section: "Integrations",
    section_priority: 50,
    category: "Unified Field",
    category_priority: 100,
    category_default_collapsed: false,
    group: "",
    group_priority: 0,
    nav_item: false,
    icon: icondata::AiSearchOutlined,
    render: || SearchSourcePickerPreview().into_any(),
};

/// Manual registration for the Unified Field icons preview page.
pub static UNIFIED_FIELD_ICONS_PREVIEW_REGISTRATION: PreviewRegistration = PreviewRegistration {
    slug: "icons/unified-field",
    label: "Unified Field",
    section: "Integrations",
    section_priority: 50,
    category: "Unified Field",
    category_priority: 100,
    category_default_collapsed: false,
    group: "",
    group_priority: 0,
    nav_item: false,
    icon: icondata::AiAppstoreOutlined,
    render: || UnifiedFieldIconsPreview().into_any(),
};

/// Manual preview pages that are not generated by `#[component_doc]`.
pub fn all() -> &'static [&'static PreviewRegistration] {
    static REGS: &[&PreviewRegistration] = &[
        &SEARCH_SOURCE_PICKER_PREVIEW_REGISTRATION,
        &UNIFIED_FIELD_ICONS_PREVIEW_REGISTRATION,
    ];
    REGS
}
