//! Preview-only components organized by category (matching Orbital's structure):
//! hand-written component previews, layout examples, motion previews, and pattern
//! previews.

/// Hand-written previews for components not covered by generated registrations
/// (search source picker, history timeline, tag catalog picker, Unified Field icons).
pub mod components;
/// Teaching widgets that demonstrate `#[component_doc]` → catalog registration.
pub mod examples;
/// Preview-only placeholder layout compositions (calendar, chat, files, etc.).
pub mod layouts;
/// Motion preview registrations (currently generated by `orbital-motion`; empty here).
pub mod motions;
/// Pattern previews (hero section, feature section, identity card).
pub mod patterns;

// `#[component_doc]` preview pages expect these names under `crate::components`.
#[cfg(feature = "preview")]
pub use orbital_core_components::preview::{ComponentPreviewCard, OrbitalComponentView};
